import { Product, Category, Group, SubCategory, SortOption } from './types';

export const dummyProducts: Product[] = [
  {
    id: '1',
    name: 'Haldiram Namkeen Mix',
    mrp: 45.99,
    productCode: 'HNM001',
    description: 'Traditional savory snacks mix with premium quality ingredients',
    expiryDate: '2025-12-31T00:00:00.000Z',
    validity: '12 months',
    stock: 150,
    stockEntryDate: '2024-01-15T00:00:00.000Z',
    lowStockLimit: 20,
    overStockLimit: 200,
    lowStockAlertColor: '#FF6B6B',
    lowStockAlertMessage: 'Low stock alert',
    overStockAlertColor: '#4ECDC4',
    overStockAlertMessage: 'Over stock alert',
    inStockAlertColor: '#45B7D1',
    inStockAlertMessage: 'In stock',
    expiryAlertDays: 30,
    expiryAlertColor: '#FFA500',
    expiryAlertMessage: 'Expiring soon',
    tags: ['namkeen', 'snacks', 'traditional'],
    imageUrl: '/namkeen-mix.jpg',
    categoryId: 'cat001',
    groupId: 'grp001',
    subCategoryId: 'sub001',
    grammage: 250,
    category: 'Namkeen',
    group: 'Snacks',
    subCategory: 'Traditional',
    inStock: true,
    isNew: true,
    isFeatured: true
  },
  {
    id: '2',
    name: 'Haldiram Sweets Assortment',
    mrp: 89.99,
    productCode: 'HSA002',
    description: 'Premium quality Indian sweets assortment',
    expiryDate: '2025-06-30T00:00:00.000Z',
    validity: '6 months',
    stock: 75,
    stockEntryDate: '2024-01-10T00:00:00.000Z',
    lowStockLimit: 15,
    overStockLimit: 100,
    lowStockAlertColor: '#FF6B6B',
    lowStockAlertMessage: 'Low stock alert',
    overStockAlertColor: '#4ECDC4',
    overStockAlertMessage: 'Over stock alert',
    inStockAlertColor: '#45B7D1',
    inStockAlertMessage: 'In stock',
    expiryAlertDays: 30,
    expiryAlertColor: '#FFA500',
    expiryAlertMessage: 'Expiring soon',
    tags: ['sweets', 'dessert', 'premium'],
    imageUrl: '/sweets.jpg',
    categoryId: 'cat002',
    groupId: 'grp002',
    subCategoryId: 'sub002',
    grammage: 500,
    category: 'Sweets',
    group: 'Desserts',
    subCategory: 'Premium',
    inStock: true,
    isFeatured: true
  },
  {
    id: '3',
    name: 'Haldiram Papad Variety Pack',
    mrp: 35.50,
    productCode: 'HPP003',
    description: 'Crispy papad varieties - perfect for any meal',
    expiryDate: '2026-03-31T00:00:00.000Z',
    validity: '18 months',
    stock: 200,
    stockEntryDate: '2024-01-20T00:00:00.000Z',
    lowStockLimit: 30,
    overStockLimit: 250,
    lowStockAlertColor: '#FF6B6B',
    lowStockAlertMessage: 'Low stock alert',
    overStockAlertColor: '#4ECDC4',
    overStockAlertMessage: 'Over stock alert',
    inStockAlertColor: '#45B7D1',
    inStockAlertMessage: 'In stock',
    expiryAlertDays: 60,
    expiryAlertColor: '#FFA500',
    expiryAlertMessage: 'Expiring soon',
    tags: ['papad', 'crispy', 'variety'],
    imageUrl: '/papad.jpg',
    categoryId: 'cat003',
    groupId: 'grp003',
    subCategoryId: 'sub003',
    grammage: 200,
    category: 'Papad',
    group: 'Accompaniments',
    subCategory: 'Crispy',
    inStock: true
  },
  {
    id: '4',
    name: 'Haldiram Ready-to-Eat Dal Khichdi',
    mrp: 25.99,
    productCode: 'HRDK004',
    description: 'Convenient and delicious dal khichdi ready in minutes',
    expiryDate: '2025-09-30T00:00:00.000Z',
    validity: '9 months',
    stock: 120,
    stockEntryDate: '2024-01-12T00:00:00.000Z',
    lowStockLimit: 25,
    overStockLimit: 150,
    lowStockAlertColor: '#FF6B6B',
    lowStockAlertMessage: 'Low stock alert',
    overStockAlertColor: '#4ECDC4',
    overStockAlertMessage: 'Over stock alert',
    inStockAlertColor: '#45B7D1',
    inStockAlertMessage: 'In stock',
    expiryAlertDays: 45,
    expiryAlertColor: '#FFA500',
    expiryAlertMessage: 'Expiring soon',
    tags: ['ready-to-eat', 'khichdi', 'convenient'],
    imageUrl: '/ready-to-eat.jpg',
    categoryId: 'cat004',
    groupId: 'grp004',
    subCategoryId: 'sub004',
    grammage: 300,
    category: 'Ready-to-Eat',
    group: 'Meals',
    subCategory: 'Traditional',
    inStock: true
  },
  {
    id: '5',
    name: 'Haldiram Aloo Bhujia',
    mrp: 32.99,
    productCode: 'HAB005',
    description: 'Crispy potato-based namkeen with authentic spices',
    expiryDate: '2025-11-30T00:00:00.000Z',
    validity: '11 months',
    stock: 180,
    stockEntryDate: '2024-01-18T00:00:00.000Z',
    lowStockLimit: 25,
    overStockLimit: 220,
    lowStockAlertColor: '#FF6B6B',
    lowStockAlertMessage: 'Low stock alert',
    overStockAlertColor: '#4ECDC4',
    overStockAlertMessage: 'Over stock alert',
    inStockAlertColor: '#45B7D1',
    inStockAlertMessage: 'In stock',
    expiryAlertDays: 30,
    expiryAlertColor: '#FFA500',
    expiryAlertMessage: 'Expiring soon',
    tags: ['namkeen', 'potato', 'spicy'],
    imageUrl: '/aloo-bhujia.jpg',
    categoryId: 'cat001',
    groupId: 'grp001',
    subCategoryId: 'sub005',
    grammage: 200,
    category: 'Namkeen',
    group: 'Snacks',
    subCategory: 'Potato',
    inStock: true
  },
  {
    id: '6',
    name: 'Haldiram Rasgulla',
    mrp: 55.99,
    productCode: 'HR006',
    description: 'Soft and spongy rasgulla in sugar syrup',
    expiryDate: '2025-05-15T00:00:00.000Z',
    validity: '5 months',
    stock: 12,
    stockEntryDate: '2024-01-05T00:00:00.000Z',
    lowStockLimit: 20,
    overStockLimit: 80,
    lowStockAlertColor: '#FF6B6B',
    lowStockAlertMessage: 'Low stock alert',
    overStockAlertColor: '#4ECDC4',
    overStockAlertMessage: 'Over stock alert',
    inStockAlertColor: '#45B7D1',
    inStockAlertMessage: 'In stock',
    expiryAlertDays: 15,
    expiryAlertColor: '#FF0000',
    expiryAlertMessage: 'Expiring very soon',
    tags: ['sweets', 'rasgulla', 'syrup'],
    imageUrl: '/rasgulla.jpg',
    categoryId: 'cat002',
    groupId: 'grp002',
    subCategoryId: 'sub001',
    grammage: 400,
    category: 'Sweets',
    group: 'Desserts',
    subCategory: 'Traditional',
    inStock: true
  },
  {
    id: '7',
    name: 'Haldiram Moong Dal Papad',
    mrp: 28.50,
    productCode: 'HMDP007',
    description: 'Healthy moong dal papad with traditional taste',
    expiryDate: '2026-01-31T00:00:00.000Z',
    validity: '15 months',
    stock: 85,
    stockEntryDate: '2024-01-25T00:00:00.000Z',
    lowStockLimit: 20,
    overStockLimit: 120,
    lowStockAlertColor: '#FF6B6B',
    lowStockAlertMessage: 'Low stock alert',
    overStockAlertColor: '#4ECDC4',
    overStockAlertMessage: 'Over stock alert',
    inStockAlertColor: '#45B7D1',
    inStockAlertMessage: 'In stock',
    expiryAlertDays: 90,
    expiryAlertColor: '#FFA500',
    expiryAlertMessage: 'Expiring soon',
    tags: ['papad', 'moong', 'healthy'],
    imageUrl: '/moong-papad.jpg',
    categoryId: 'cat003',
    groupId: 'grp003',
    subCategoryId: 'sub006',
    grammage: 150,
    category: 'Papad',
    group: 'Accompaniments',
    subCategory: 'Healthy',
    inStock: true
  },
  {
    id: '8',
    name: 'Haldiram Paneer Curry',
    mrp: 42.99,
    productCode: 'HPC008',
    description: 'Rich and creamy paneer curry ready to serve',
    expiryDate: '2025-08-20T00:00:00.000Z',
    validity: '8 months',
    stock: 45,
    stockEntryDate: '2024-01-08T00:00:00.000Z',
    lowStockLimit: 15,
    overStockLimit: 60,
    lowStockAlertColor: '#FF6B6B',
    lowStockAlertMessage: 'Low stock alert',
    overStockAlertColor: '#4ECDC4',
    overStockAlertMessage: 'Over stock alert',
    inStockAlertColor: '#45B7D1',
    inStockAlertMessage: 'In stock',
    expiryAlertDays: 60,
    expiryAlertColor: '#FFA500',
    expiryAlertMessage: 'Expiring soon',
    tags: ['ready-to-eat', 'paneer', 'curry'],
    imageUrl: '/paneer-curry.jpg',
    categoryId: 'cat004',
    groupId: 'grp004',
    subCategoryId: 'sub007',
    grammage: 350,
    category: 'Ready-to-Eat',
    group: 'Meals',
    subCategory: 'Curry',
    inStock: true,
    isNew: true
  }
];

export const categories: Category[] = [
  { id: 'all', name: 'All Products' },
  { id: 'cat001', name: 'Namkeen' },
  { id: 'cat002', name: 'Sweets' },
  { id: 'cat003', name: 'Papad' },
  { id: 'cat004', name: 'Ready-to-Eat' }
];

export const groups: Group[] = [
  { id: 'grp001', name: 'Snacks' },
  { id: 'grp002', name: 'Desserts' },
  { id: 'grp003', name: 'Accompaniments' },
  { id: 'grp004', name: 'Meals' }
];

export const subCategories: SubCategory[] = [
  { id: 'sub001', name: 'Traditional' },
  { id: 'sub002', name: 'Premium' },
  { id: 'sub003', name: 'Crispy' },
  { id: 'sub004', name: 'Convenient' },
  { id: 'sub005', name: 'Potato' },
  { id: 'sub006', name: 'Healthy' },
  { id: 'sub007', name: 'Curry' }
];

export const sortOptions: SortOption[] = [
  { id: 'featured', name: 'Featured' },
  { id: 'price-low', name: 'Price: Low to High' },
  { id: 'price-high', name: 'Price: High to Low' },
  { id: 'stock-high', name: 'Stock: High to Low' },
  { id: 'stock-low', name: 'Stock: Low to High' },
  { id: 'expiry-soon', name: 'Expiring Soon' },
  { id: 'newest', name: 'Newest First' }
];
